##################################################################################################
# Productpage services
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mybookinfo-sa
  namespace: mybookinfo
---
apiVersion: v1
kind: Service
metadata:
  name: productpage
  namespace: mybookinfo
  labels:
    app: productpage
    service: productpage
spec:
  ports:
    - name: http
      port: 9080
      targetPort: 9080
      # 固定端口数值，必须是配置文件范围内
      nodePort: 30000
  type: NodePort
  selector:
    app: productpage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
  namespace: mybookinfo
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      serviceAccountName: mybookinfo-sa
      containers:
        - name: productpage
          image: productpage:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICES_DOMAIN
              value: "mybookinfo.svc"
          ports:
            - containerPort: 9080
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}