spring:
  application:
    name: discovery-eureka-server
#security:  #注释掉spring-cloud-starter-security
#  basic:
#    enabled: true
#  user:
#    name: admin
#    password: admin
server:
  port: 8761
eureka:
  #instance-id3 : ${spring.application.name}:${server.port}:@project.version@
  client:
    #声明自己是个服务端
    registerWithEureka: false    #false表示不向注册中心注册自己
    fetchRegistry: false         #false表示自己就是注册中心，职责是维护实例，不参加检索
    serviceUrl:                  #设置eureka server的交互地址，即对外暴露的地址
    #  defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  # 配置使用主机名注册服务
  instance:
    hostname: localhost
  # 优先使用IP地址方式进行注册服务
  #prefer-ip-address: true
    
#---
#spring:
#  profiles: eureka1
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: eureka-server
#  client:
#    #声明自己是个服务端
#    #registerWithEureka: false    #false表示不向注册中心注册自己
#    #fetchRegistry: false         #false表示自己就是注册中心，职责是维护实例，不参加检索
#    serviceUrl:                  #设置eureka server的交互地址，即对外暴露的地址
#      defaultZone: http://eureka:123@eureka2:8762/eureka/
#  server:
#    enable-self-preservation: false
#---
#spring:
#  profiles: eureka2
#server:
#  port: 8762
#eureka:
#  instance:
#    hostname: eureka2
#  client:
#    #声明自己是个服务端
#    #registerWithEureka: false    #false表示不向注册中心注册自己
#    #fetchRegistry: false         #false表示自己就是注册中心，职责是维护实例，不参加检索
#    serviceUrl:                  #设置eureka server的交互地址，即对外暴露的地址
#      defaultZone: http://eureka:123@eureka1:8761/eureka/
#  server:
#    enable-self-preservation: false