apiVersion: v1
kind: ServiceAccount
metadata:
  name: mybookinfo-sa
  namespace: otherns
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: otherns
  name: sc-k8s-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  sc-k8s-reader-binding
  namespace: otherns
subjects:
  - kind: ServiceAccount
    name: mybookinfo-sa
    apiGroup: ""
roleRef:
  kind: Role
  name: sc-k8s-reader
  apiGroup: ""