server:
  port: 8101

spring:
  application:
    name: ratings
  datasource:
    #platform: h2
    #url: jdbc:h2:mem:reviews;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    #username: sa
    #password:
    #driver-class-name: org.h2.Driver
    platform: ${DATASOURCE_PLATFORM:pg}
    url: ${DATASOURCE_URL:jdbc:postgresql://192.168.92.1:5432/ratingdb}
    username: ${DATASOURCE_USERNAME:bookinfo}
    password: ${DATASOURCE_PASSWORD:bookinfo}
    driver-class-name: ${DATASOURCE_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:none}
    show-sql: false

  cloud:
    nacos:
      discovery:
        #nacos的服务地址
        server-addr: 192.168.92.3:31848
        #nacos的命名空间，用来标记应用组，可以互相发现的一组微服务。对应nacos控制台的namespace  id。
        namespace: bookinfo
        # 分组，用来标记运行环境 dev prd等等
        group: dev
        # 默认是应用的name，一组提供相同服务的服务实例
        #service: {spring.application.name}

#eureka:
#  client:
#    service-url:
#      #defaultZone: http://eureka:123@eureka1:8761/eureka/,http://eureka:123@eureka2:8762/eureka/
#      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    metadata-map:
#      addr: shenzhen china
#      tel: 0755-10001