spring:
  application:
    name: ratings
  datasource:
    #platform: h2
    #url: jdbc:h2:mem:reviews;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    #username: sa
    #password:
    #driver-class-name: org.h2.Driver
    platform: ${DATASOURCE_PLATFORM:pg}
    url: ${DATASOURCE_URL:"jdbc:postgresql://192.168.92.1:5432/ratingdb"}
    username: ${DATASOURCE_USERNAME:bookinfo}
    password: ${DATASOURCE_PASSWORD:bookinfo}
    driver-class-name: ${DATASOURCE_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:none}
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
server:
  port: 8101