spring:
  application:
    name: details
server:
  port: 8103

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
    env:
      enabled: true
    info:
      enabled: true
    mappings:
      enabled: true

  endpoints:
    # 暴露 EndPoint 以供访问，有jmx和web两种方式，exclude 的优先级高于 include
    web:
      exposure:
        #exclude: '*'
        include: ["health","info","mappings","metrics","env","myHealth","prometheus"]
      base-path: /actuator  # 配置 Endpoint 的基础路径
    enabled-by-default: false # 修改全局 endpoint 默认设置