spring:
  application:
    name: details
server:
  port: 8103

eureka:
  client:
    service-url:
      #defaultZone: http://eureka:123@eureka1:8761/eureka/,http://eureka:123@eureka2:8762/eureka/
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      addr: shenzhen china
      tel: 0755-10001