spring:
  application:
    name: details
server:
  port: 8103
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
    env:
      enabled: true
    info:
      enabled: true
    mappings:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ["health","info","mappings","metrics","env","healthz","prometheus"]
      base-path: /actuator  # 配置 Endpoint 的基础路径
    enabled-by-default: false # 修改全局 endpoint 默认设置
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  client:
    service-url:
      #defaultZone: http://eureka:123@eureka1:8761/eureka/,http://eureka:123@eureka2:8762/eureka/
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      addr: shenzhen china
      tel: 0755-10001